version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ohmydog
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - ohmydog

  node_app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - ohmydog
    environment:
      PORT: 3000
      DATABASE_URL: "postgresql://admin:1234@db:5432/ohmydog?schema=public"

networks:
  ohmydog:
    driver: bridge